# Generated by Django 5.1.7 on 2025-03-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_alter_servicerequest_status'),
    ]

    operations = [
    ]
